### ISSUE TITLE
Add a 'use string literally' search option

### ISSUE THREAD

**Issue by Wilfred** [hound-search/hound#186]
Sometimes I want to search for some code that contains regexp metacharacters, e.g. I want to search `foo.baz[bar]()`. It would be nice to have an option in the UI to do this -- I find it takes some thought to work out it's `foo\.baz\[bar\]\(\)`.

**Comment by dgryski** [comment]
Probably straight forward to add a "quotemeta" option  and pass the query to https://golang.org/pkg/regexp/#QuoteMeta if present.

**Comment by electrofelix** [comment]
Use case: Cutting and pasting part or all of a line of code to search for it seems like a common operation, and since code frequently will contain characters that are special in regex terms, currently I find I need to edit the line after pasting instead of just cut/paste/search. The number of times I need to do a regex search for code has been relatively low, but an additional click or key press on top of typing in a regex for code seems like a very small increase in input for that use case compared to the cut/paste/search.

I think it would be useful to be able to make this the default through the UI, with the option to switch the search to regexp/plain depending on the site default, and leave it up to site admins to determine based on usage which is most useful default for their users.

**Comment by StingyJack** [comment]
> The number of times I need to do a regex search for code has been relatively low..

For me its so low its almost _never_. The only time I think I've ever tried a regex for code searching was trying to count LOC using Visual Studio's find tool (it didnt work anyway). 

I'm searching code to find usages, so I already know the identifier. Literal should be the default.

**Comment by NightMachinary** [comment]
It would also be much more intuitive if whitespace was treated as `AND` ala `fzf`.
