### ISSUE TITLE
GOPATH variable is empty even after successful installation

### ISSUE THREAD

**Issue by anujsharma12feb** [hound-search/hound#241]
I have installed go tools in ubuntu 14.04. But $GOPATH variable is coming as null even after successful installation. To fix the same, i have manually exported the $GOPATH.

I would like to suggest to make the same change in README.md such that it will be helpful for any newbie.

**Comment by anujsharma12feb** [comment]
I would like to make the change if Authors are happy for the change.
Recommended change is:
https://github.com/anujsharma12feb/hound/commit/5ece28809cd03893cfa696dd924c26d78153398a

**Comment by salemhilal** [comment]
I think the assumption here is that you have Go set up properly on your development machine. I'm a bit new at this, but I believe `$GOPATH` is something that you're responsible for setting yourself, rather than our installation.

See here for more:
https://golang.org/doc/gopath_code.html#GOPATH

I'm going to close this for now, but if you still have questions, feel free to reopen it and we'll be happy to help out.
