### ISSUE TITLE
Adding UI configuration

### ISSUE THREAD

**Issue by jonesetc** [hound-search/hound#253]
It would be useful to add in the ability for setting some UI configuration. One use case is that my team uses hound to search our private repos, but we almost universally want to do case insensitive searches. It would be great if we could just drop in a config file for the UI as well as the main service to control this.

A possibility for this would be support dropping in a `config.js` file into `ui/assets/js`, and in the server just check if that file exists and render it inside of some script tags just like the main `hound.js`. For our specific use case we would also need to add in a check for a `defaultIcase` and use that [here](https://github.com/etsy/hound/blob/effbe5873f329fcdf982e906b756b535e2804ebc/ui/assets/js/hound.js#L501).

If a simple approach like this seems agreeable, then I could put together a quick attempt.

Thank you

**Comment by dschott68** [comment]
Hi, if you have interest and time, please do submit a Pull Request.  Cheers!

**Comment by salemhilal** [comment]
Seconded, and it could be cool to see a list of things that would be turned into features.

One thought is that it could be interesting to include it as a key in the same config, to reduce the need to manage two separate files. Another thought is that we could use a Webpack loader to provide access to the config's values at build time, instead of adding an additional script tag to the page.
