### ISSUE TITLE
git: support submodules

### ISSUE THREAD

**Issue by bd808** [hound-search/hound#277]
It would be nice to have the git driver at least optionally support repos which are using submodules. A concrete use case is https://phabricator.wikimedia.org/T188023

**Comment by legoktm** [comment]
> If the objective is to be able to search a repository for code, having one repository return code from another might make the results confusing.

The idea is that we can search through all of the code we deploy, which might include submodules. @bd808 asked for it to be an option, which I think addresses any potential confusion if you have to explicitly opt-in to it.

> I'm going to close this for now, but if there's a reason that supporting submodules, rather than adding each repository separately, feel free to reopen this issue.

The main advantage to using a submodule is that it would index the version of the code that is actually in the submodule, rather than having another repository which indexes master. I'd appreciate if you could re-open this.

**Comment by salemhilal** [comment]
@legoktm I think I may not be understanding this properly. If I have some string `S` that shows up in both a repository `R` and in a submodule `M`, and I query for `S`, would the results show both strings under the results for `R`, or would there be a separate group of results for `M`? And would `R` and `M` both show up in the "Select Repo" input in the advanced search?
