### ISSUE TITLE
Idea for documentation search

### ISSUE THREAD

**Issue by Katherine-Bishop** [hound-search/hound#293]
Engineers like putting documentation in Github next to their code, but if you search in Hound for a keyword in Markdown-formatted files, there is a good chance of getting a ton of irrelevant results because the ranking of search results doesn’t take into account the document structure.

In the case of Markdown-formatted documentation search the most relevant results are the documents with matches in headings and tag metadata.

We would like to extend Hound to have a custom user interface for documentation search that composes several regular expressions based on search query and uses custom rankings to show the most relevant documents first.

Or in a more general way to make it usable for other formats like Asciidoc or Org-Mode documents, we may add an extension point to the Hound UI that allows for the specification of predefined search patterns and custom search results ranking strategy.

What do you think? We are ready to make a PR.

**Comment by Katherine-Bishop** [comment]
I have gotten a rough prototype of the idea working. The code for it can be found [here](https://github.com/Katherine-Bishop/hound/commit/a347ce345d1e7a0c5ca52b1666d9fc441841ea63) in my fork. I configured an instance of Hound to point at this [repo of frontend documentation](https://github.com/FrontendMasters/front-end-handbook). Here are a few screenshots of what the documentation search looks like in action. Let me know what you think @stanistan @mrtazz @kevingessner @kellegous 

**Without documentation search:**
![hound_no_doc_search](https://user-images.githubusercontent.com/2836756/45456200-ddb99e80-b6b7-11e8-801e-30f43d17de6c.png)

**With documentation search:**
![hound_doc_search](https://user-images.githubusercontent.com/2836756/45456199-ddb99e80-b6b7-11e8-994b-6d9076674ce1.png)

**Comment by salemhilal** [comment]
I think that in the near term, tailoring Hound specifically for documentation might be too specific of a goal. I don't think it's a bad idea to provide some additional tools to make it easier to get results for queries directed at documentation though. For example, while having a documentation-specific option might be too narrow, having an option to sort results based on a relevancy algorithm (kinda like what ElasticSearch uses) instead of by alphabetical order might be really useful across a bunch of contexts.

I'm going to close this issue for now, but I'm definitely open to re-opening it or accepting pull requests for something like relevancy-based ordering.
