### ISSUE TITLE
Submit form via POST rather than GET

### ISSUE THREAD

**Issue by richardjq** [hound-search/hound#399]
Please consider having hound submit search requests via post (or maybe make it optional?). 

If you are indexing _many, many_  repos and when you want to restrict your search to just _many_ of them, the URI is quite long. If you run hound behind a web application firewall this is likely to be seen as an attack and result in a "414 Request-URI Too Long".

Thanks for considering.

**Comment by salemhilal** [comment]
Hey! That does sound like a problem. Generally speaking, I don't think that POST requests are the right HTTP verb to use here, since we're not updating anything and since these requests could be cached safely for a short period of time. Is there any option to configure your firewall to allow long URLs just for your Hound instance?

**Comment by richardjq** [comment]
Yep.  I can reconfigure our firewall. I was just submitting this issue in order to try to help others who run into this problem. If you don't want to change the HTTP verb, I guess we can just close this.

Thanks for considering.

**Comment by richardjq** [comment]
Allowing the user to specify the repos to be searched by regex (rather than selecting every single one) might also mitigate this problem.

**Comment by richardjq** [comment]
Yes. We tend to organize our repos (in gitlab) hierarchically. And since we have 3000+ groups, a regex or glob would help a great deal.

**Comment by salemhilal** [comment]
Closing this in favor of #411. Thanks again, and feel free to reopen this issue if you think I'm missing some context.
