### ISSUE TITLE
two factor auth for github

### ISSUE THREAD

**Issue by nurey** [hound-search/hound#5]
Does this support two factor authentication for github?

**Comment by cfurrow** [comment]
Does not seem to. Had to generate a personal access token for it via https://github.com/settings/applications

And even after supplying that, the houndd app seems to need my github username/access token ever few minutes to check for changes. Kind of odd.

**Comment by dlanger** [comment]
It supports it in the same way that most applications that need continuous access to a 2FA service do, which is that they need you to create a token. Once you create a [personal access token](https://github.com/settings/applications), you've now effectively got a password that doesn't need 2FA.

Once you've got that set, your problem is that Git keeps asking for your password when it polls the repos - so you need a [credential helper](http://git-scm.com/docs/gitcredentials). The simplest - and most insecure - one is `store`, which keeps all your usernames and passwords on disk in a clear-text file. To enable this, do `git config --global credential.helper 'store'`, after which you'll be asked for your password once and only once. You could also use a [gpg-encrypted `.netrc` file](http://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-github/18362082#18362082), but that's a little more complex.

In all, this seems like something we can handle at the `git` level (with some better docs), as opposed to in the product itself.
